version: '3.7'

services:
    server:
      build:
        context: .
        dockerfile: Dockerfile
      image: eportfolio-nodeserver-img
      container_name: node-express
      volumes:
       - .:/usr/src/app
       - /usr/src/app/node_modules
      ports:
        - "8080:8080"
      depends_on:
        - mongo
      env_file: .env
      environment:
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
    mongo:
      image: mongo
      container_name: eportfolio-mongodb
      ports:
        - "27017:27017"